import Head from 'next/head'
import Image from "next/image";
import Link from "next/link";
import HomePageExtraInfo from "../common/HomePageExtraInfo"
import WorkSection from "../common/WorkSection"
import React, { useRef, useEffect } from 'react';
import Navbar from '../../src/common/navbar.jsx';
import { useRouter } from 'next/router';

export default function Home() {
  const router = useRouter();
  const workRef = useRef(null);

  useEffect(() => {
    if (router.query.scrollTo === 'work') {
      workRef.current?.scrollIntoView({ behavior: 'smooth' });
    }
  }, [router.query.scrollTo]); // Depend on the scrollTo query parameter


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="./output.css" rel="stylesheet" />
      </Head>
      <Navbar />
      <main className="w-full h-screen">
        <div className="home-wrapper" style={{ height: "calc(100vh - 300px)" }}>
          <div className="cross-hair-grid">

            <div className="cross-hairs">
              {[...Array(20)].map((_, index) => (
                <div className="cross-hair" key={index}>
                  <Image
                    className="sky"
                    src="/Images/Home/crosshairSmall.svg"
                    alt="crosshair"
                    width="100"
                    height="100"
                  />
                </div>
              ))}
            </div>
          </div>
          <div className="one hidden md:block">
            <div className="box1"></div>
            <div className="box2"></div>
          </div>
          <div class="mt-5 md:mt-10 h-full flex items-center">
            <div class="w-full md:w-9/12">
              <div class="px-0 md:px-8 lg:px-32">
                <Link href="mailto:glasserben@gmail.com" target="_blank">
                  <Image class="sky-gif w-full" src="/Images/Home/sky.gif" alt="generative sky" width="100"
                    height="100" />
                </Link>
                <HomePageExtraInfo />
                <div class="border-b mt-5 md:mt-10"></div>
              </div>
            </div>
          </div>
        </div>
      </main>
      <div ref={workRef}>
        <WorkSection />
      </div>
    </>
  )
}


